title: Opeyemi Fabiyi # your name (or website title) here
logo: "images/Image%20from%20iOS%20(2).jpga" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/opeyemifabiyi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-slate
